<dec f='include/python3.8/pyerrors.h' l='18' type='void PyErr_Restore(PyObject * , PyObject * , PyObject * )'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/common.h' l='770' u='c' c='_ZN8pybind1111error_scopeD1Ev'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/pytypes.h' l='340' u='c' c='_ZN8pybind1117error_already_set7restoreEv'/>
