<dec f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.h' l='669' type='void lldb_private::python::PythonException::log(llvm::raw_ostream &amp; OS) const'/>
<inh f='llvm/llvm/include/llvm/Support/Error.h' l='53' c='_ZNK4llvm13ErrorInfoBase3logERNS_11raw_ostreamE'/>
<def f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1061' type='void lldb_private::python::PythonException::log(llvm::raw_ostream &amp; OS) const'/>
