<dec f='include/python3.8/pyerrors.h' l='35' type='int PyErr_ExceptionMatches(PyObject * )'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='4330' u='c' c='_ZN13PyErr_CleanerD1Ev'/>
