<dec f='include/python3.8/pyerrors.h' l='67' type='PyObject *'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.h' l='702' u='r' c='_ZN12lldb_private6python26unwrapOrSetPythonExceptionEN4llvm8ExpectedIT_EE'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1049' u='r' c='_ZN12lldb_private6python15PythonException7RestoreEv'/>
