<dec f='include/python3.8/pyerrors.h' l='92' type='PyObject *'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='876' u='r' c='_ZL21SWIG_Python_ErrorTypei'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='903' u='r' c='_ZL21SWIG_Python_ErrorTypei'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='931' u='r' c='_ZL23SWIG_Python_AddErrorMsgPKc'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='1313' u='r' c='_ZL25SWIG_Python_ExceptionTypeP14swig_type_info'/>
