<dec f='include/python3.8/pyerrors.h' l='17' type='void PyErr_Fetch(PyObject ** , PyObject ** , PyObject ** )'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/common.h' l='769' u='c' c='_ZN8pybind1111error_scopeC1Ev'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/pytypes.h' l='329' u='c' c='_ZN8pybind1117error_already_setC1Ev'/>
